import type { TranscriptAnalysis, HighlightMetric, CapexSegment, RevenueSegment, EbitdaSegment } from './types'

export const PRIMARY_ANALYSIS: TranscriptAnalysis = {
  ticker: 'ADANIENT',
  quarter: 'Q2 & H1 FY26',
  company_name: 'Adani Enterprises Limited',
  call_date: 'November 04, 2025',
  executive_summary:
    'Adani Enterprises Limited delivered consolidated total income of INR 44,281 crores and EBITDA of INR 7,688 crores for H1 FY26, driven by incubating businesses which now contribute over 70% of total group EBITDA. Key capital assets transitioned into commercial operations during the period, notably the 500 KTPA Kutch Copper plant, Phase 1 of the Greenfield Navi Mumbai International Airport, and key road expressway projects. To de-lever the balance sheet and fund accelerated infrastructure development across airports and clean energy ecosystems, the board authorized an equity rights issue of up to INR 25,000 crores to convert promoter loans into equity.',
  financial_health: {
    revenue_trend:
      'Consolidated H1 total income reached INR 44,281 crores, buoyed by a 32% YoY surge in airport revenue to INR 5,882 crores and a 35% YoY increase in MDO revenue to INR 2,247 crores, despite cyclical trade and commodity price volatility and a 5% half-yearly contraction in solar module revenues.',
    margin_guidance:
      'Incubating business EBITDA contribution expanded from 60% to over 70% YoY with airport quarterly EBITDA run-rate exceeding INR 1,000 crores (+51% YoY in H1), while solar manufacturing EBITDA dropped 14% due to U.S. tariff-induced pricing adjustments expected to normalize over the next 18 months.',
    capex_updates:
      'H1 FY26 capex stood at INR 16,300 crores with full-year guidance targeted at ~INR 36,000 crores (including INR 10,500 crores for airports, INR 9,000 crores for materials/petrochemicals, INR 6,000 crores for roads, and INR 5,500 crores for ANIL), alongside accelerated Phase 2 airport capex of ~INR 30,000 crores and an outlay of ~INR 20,000 crores for City Side Development.',
  },
  hidden_risks: [
    'U.S. Solar Tariff Uncertainty and Repricing Pressures: Ongoing trade policy volatility and tariff announcements from the U.S. forced immediate pricing rationalization in module sales, dampening ANIL EBITDA by 14% with an extended 18-month adjustment period required before margins normalize.',
    'Litigation and Environmental Clearance Delays on Real Estate: City Side Development (CSD) commercial revenue generation has been postponed to FY 2029-2030 as excavation and site progress were previously stalled by Supreme Court litigation and environmental clearance restrictions in Mumbai.',
    'Working Capital Absorption and Promoter Loan Restructuring Dependency: Operating cash flow fell sharply due to inventory build-up from Kutch Copper transitioning to commercial operations, while the massive INR 25,000 crore rights issue is substantially dedicated to absorbing ~INR 20,000 crore of shareholder/promoter debt rather than generating immediate unencumbered cash flow.',
  ],
  sentiment_analysis: {
    score: 6.2,
    rationale:
      'Management displayed firm confidence regarding core infrastructure commissioning milestones and balance sheet deleveraging, but pivoted defensively into confidentiality agreements and premature pilot testing when pressed for concrete financials on the Google AI data center, green hydrogen electrolyzer efficiency curves, and compressed operational cash flows.',
  },
}

export const CORE_METRICS: HighlightMetric[] = [
  {
    label: 'Consolidated H1 Revenue',
    value: '₹44,281 Cr',
    subtext: '+32% Airport & +35% MDO growth',
    trend: 'positive',
  },
  {
    label: 'Consolidated EBITDA',
    value: '₹7,688 Cr',
    subtext: '70%+ generated by incubating assets',
    trend: 'positive',
  },
  {
    label: 'FY26 Target CapEx',
    value: '₹36,000 Cr',
    subtext: '₹16,300 Cr deployed in H1 (Airports lead)',
    trend: 'neutral',
  },
  {
    label: 'Rights Issue Equity Plan',
    value: '₹25,000 Cr',
    subtext: 'Converting ₹20,000 Cr promoter loans',
    trend: 'neutral',
  },
]

export const CAPEX_SEGMENTS: CapexSegment[] = [
  { segment: 'Airports', actual: 5800, target: 10500, color: '#3b82f6' },
  { segment: 'Materials & Petrochem', actual: 4200, target: 9000, color: '#06b6d4' },
  { segment: 'Roads', actual: 3300, target: 6000, color: '#10b981' },
  { segment: 'ANIL (Clean Energy)', actual: 3000, target: 5500, color: '#f59e0b' },
  { segment: 'City Side Dev.', actual: 0, target: 5000, color: '#ec4899' },
]

export const REVENUE_GROWTH: RevenueSegment[] = [
  { segment: 'Airport', growth: 32, revenue: '₹5,882 Cr' },
  { segment: 'MDO', growth: 35, revenue: '₹2,247 Cr' },
  { segment: 'Solar Modules', growth: -5, revenue: '₹1,890 Cr' },
  { segment: 'Copper', growth: 28, revenue: '₹3,120 Cr' },
  { segment: 'Roads', growth: 18, revenue: '₹2,450 Cr' },
]

export const EBITDA_BREAKDOWN: EbitdaSegment[] = [
  { segment: 'Incubating Businesses', percentage: 70, color: '#3b82f6' },
  { segment: 'Established Businesses', percentage: 30, color: '#64748b' },
]

export const SENTIMENT_SCALE = {
  min: -10,
  max: 10,
  zones: [
    { from: -10, to: -6, label: 'Bearish', color: '#ef4444' },
    { from: -6, to: -2, label: 'Cautious', color: '#f97316' },
    { from: -2, to: 2, label: 'Neutral', color: '#eab308' },
    { from: 2, to: 6, label: 'Optimistic', color: '#22c55e' },
    { from: 6, to: 10, label: 'Confident', color: '#10b981' },
  ],
}
